#!/usr/bin/env perl

=head1 NAME

pversion - show installed version of supplied Perl modules

=head1 SYNOPSIS

 pversion Some::Module Another::Module

=head1 DESCRIPTION

This script just loops through the supplied list of Perl module
names, attempts to load them and display their VERSION number.

=head1 AUTHOR

Rufus Cable <rufus@threebytesfull.com>

=head1 LICENSE

Copyright 2009 Rufus Cable

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=cut

for my $module (@ARGV) {
    my $version;
    eval "use $module; \$version = $module->VERSION;";
    print "$module: ".($version || '???')."\n";
}
